apiVersion: v1
kind: Service
metadata:
  name: sentinel-svc
  labels:
    app: sentinel
spec:
  ports:
    - name: sentinel
      protocol: "TCP"
      port: 8858
      targetPort: 8858
      nodePort: 30101
 #   - name: sentinel-p
 #     protocol: "TCP"
 #     port: 8719
 #     targetPort: 8719
 #     nodePort: 8719
  type: NodePort
  selector:
    app: sentinel
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sentinel
spec:
  serviceName: sentinel
  replicas: 2
  selector:
    matchLabels:
      app: sentinel
  template:
    metadata:
      labels:
        app: sentinel
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
        - name: sentinel
          image: bladex/sentinel-dashboard:latest
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
          ports:
            - containerPort: 8858
              name: sentinel-client
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JAVA_OPTS
              value: "-Dserver.port=8858 -Dcsp.sentinel.dashboard.server=localhost:8858 -Dproject.name=sentinel  -Dcsp.sentinel.api.port=8719"
